######################################################################
# Automatically generated by qmake (2.01a) Sat May 23 05:33:56 2015
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += testwidget.h
SOURCES += main.cc testwidget.cc
