######################################################################
# Automatically generated by qmake (2.01a) Sat Jun 13 03:11:14 2015
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += mainwidget.h msg.h mychatwidget.h mylogwidget.h myselectfacewidget.h
SOURCES += main.cc \
           mainwidget.cc \
           mychatwidget.cc \
           mylogwidget.cc \
           myselectfacewidget.cc
