######################################################################
# Automatically generated by qmake (2.01a) Tue May 5 03:38:46 2015
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += calculator.h mystack.h mywidget.h
SOURCES += calculator.cc main.cc mywidget.cc
